const BOSSES = [
  { id: "venatus", en: "Venatus", ja: "ベナトゥス", ko: "베나투스", points: 0 },
  { id: "viorent", en: "Viorent", ja: "ビオレント", ko: "비오렌트", points: 0 },
  { id: "ego", en: "Ego", ja: "エゴ", ko: "에고", points: 0 },
  { id: "clemantis", en: "Clemantis", ja: "クレメンティス", ko: "클레멘티스", points: 0 },
  { id: "livera", en: "Livera", ja: "リベラ", ko: "리베라", points: 0 },
  { id: "araneo", en: "Araneo", ja: "アラネオ", ko: "아라네오", points: 0 },
  { id: "undomiel", en: "Undomiel", ja: "アンドゥミエル", ko: "안두미엘", points: 0 },
  { id: "saphirus", en: "Saphirus", ja: "サピルス", ko: "사피루스", points: 0 },
  { id: "neutro", en: "Neutro", ja: "ネウトロ", ko: "네우트로", points: 0 },
  { id: "lady_dalia", en: "Lady Dalia", ja: "レディ·ダリア", ko: "레이디 달리아", points: 0 },
  { id: "general_aquleus", en: "General Aquleus", ja: "将軍アクレウス", ko: "장군 아클레우스", points: 0 },
  { id: "thymele", en: "Thymele", ja: "テュメレ", ko: "튜메레", points: 0 },
  { id: "amentis", en: "Amentis", ja: "アメンティス", ko: "아멘티스", points: 0 },
  { id: "baron_braudmore", en: "Baron Braudmore", ja: "ブラウドモア", ko: "남작 브라우드모어", points: 0 },
  { id: "milavy", en: "Milavy", ja: "ミラベ", ko: "미라베", points: 0 },
  { id: "wannitas", en: "Wannitas", ja: "ワニタス", ko: "와니타스", points: 0 },
  { id: "metus", en: "Metus", ja: "メトゥス", ko: "메투스", points: 0 },
  { id: "duplican", en: "Duplican", ja: "デュプリカン", ko: "듀플리칸", points: 0 },
  { id: "shuliar", en: "Shuliar", ja: "シュライヤー", ko: "슈라이어", points: 0 },
  { id: "ringor", en: "Ringor", ja: "リンゴル", ko: "링고르", points: 0 },
  { id: "roderick", en: "Roderick", ja: "ロデリック", ko: "로데릭", points: 0 },
  { id: "gareth", en: "Gareth", ja: "ガレス", ko: "가레스", points: 0 },
  { id: "titore", en: "Titore", ja: "ティトル", ko: "티토르", points: 0 },
  { id: "larba", en: "Larba", ja: "ラルバ", ko: "라르바", points: 0 },
  { id: "catena", en: "Catena", ja: "カテナ", ko: "카테나", points: 0 },
  { id: "auraq", en: "Auraq", ja: "アウラーク", ko: "아우라크", points: 0 },
  { id: "secreta", en: "Secreta", ja: "セクレタ", ko: "세크레타", points: 0 },
  { id: "ordo", en: "Ordo", ja: "オルド", ko: "오르도", points: 0 },
  { id: "asta", en: "Asta", ja: "アスタ", ko: "아스타", points: 0 },
  { id: "supore", en: "Supore", ja: "スポル", ko: "스포르", points: 0 },
  { id: "chaiflock", en: "Chaiflock", ja: "シャイフロック", ko: "샤이플록", points: 0 },
  { id: "benji", en: "Benji", ja: "ベンジー", ko: "벤지", points: 0 },
  { id: "libitina", en: "Libitina", ja: "リビティーナ", ko: "리비티나", points: 0 },
  { id: "rakajeth", en: "Rakajeth", ja: "ラカゼス", ko: "라카제스", points: 0 },
  { id: "icaruthia", en: "Icaruthia", ja: "イカルシア", ko: "이카루시아", points: 0 },
  { id: "motti", en: "Motti", ja: "モティ", ko: "모티", points: 0 },
  { id: "camalia", en: "Camalia", ja: "カマリア", ko: "카말리아", points: 0 },
  { id: "nevaeh", en: "Nevaeh", ja: "ネバ", ko: "네바", points: 0 },
  { id: "tumier", en: "Tumier", ja: "トゥミエル", ko: "투미엘", points: 0 },
  { id: "lucus", en: "Lucus", ja: "ルクス", ko: "루크스", points: 0 }
];
